export const CHANGE_LAST_USED_WORD = 'CHANGE_LAST_USED_WORD';
export const CHANGE_GAME_STATUS = 'CHANGE_GAME_STATUS';
export const CHANGE_GAME_TURN = 'CHANGE_GAME_TURN';
export const RESTART_GAME = 'RESTART_GAME';
export const END_GAME = 'END_GAME';
